# Generated by Django 6.1 on 2026-09-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_profile_role_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='interval_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
