# Generated by Django 6.1 on 2026-09-18 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_profile_pan_no_recurringtransaction_interval_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='template',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='currency',
            field=models.CharField(default='NPR', max_length=8),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='merchant',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='interval',
            field=models.CharField(default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='next_run',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
